### ISSUE TITLE
[quill] 프로젝트 시작

### ISSUE THREAD

**Issue by PyeonSangJin** [Quill-io/quill-backend#1]
### project specs
language: kotlin
type: gradle-kotlin
java: version 8
jdk: version 1.8.0_332
package: jar
gradle: 7.4
db: r2dbc
db-driver: jasync-sql

**Comment by PyeonSangJin** [comment]
@CKANYWHERE 님, 아래 내용 참고 부탁드립니다.

- 브랜치 컨벤션 : feature/{이슈번호}/{브랜치이름} 
  - ex) `feature/2/makeUserFunc`
- 커밋 컨벤션: [#{이슈번호}] {커밋 내용}
  - ex) `[#1] 프로젝트 시작`

**Comment by CKANYWHERE** [comment]
Reviewed
